-- Insert sample categories
INSERT INTO public.categories (name, slug) VALUES
('Next.js', 'nextjs'),
('React', 'react'),
('Web', 'web'),
('CSS', 'css'),
('Backend', 'backend')
ON CONFLICT (name) DO NOTHING;

-- Insert sample posts
INSERT INTO public.posts (title, excerpt, content, category_id, image_url) VALUES
('Why Next.js 15 is a Game Changer', 'Discover the full potential of Next.js 15 routing and rendering paradigms.', '## 서론\n\n최근 프론트엔드 생태계에서 가장 주목받는 업데이트 중 하나는 바로 Next.js 15의 등장입니다. 이 버전은 단순히 기능 추가를 넘어 개발자와 사용자 모두에게 전에 없던 혁신적인 경험을 제공합니다.\n\n### 주요 변경 사항\n\n1.  **향상된 App Router**: 데이터 패칭과 캐싱 전략이 더욱 정교해졌습니다.\n2.  **Turbopack 도입**: 로컬 개발 서버의 구동 속도와 HMR(Hot Module Replacement) 성능이 비약적으로 향상되었습니다.\n3.  **React 19 완벽 지원**: Server Actions와 새로운 훅들을 완벽하게 지원하여, 복잡한 상태 관리 없이도 매끄러운 데이터 뮤테이션이 가능해졌습니다.\n\n### 성능의 진화\n\n과거 버전들과 비교했을 때, 빌드 속도와 런타임 성능에서 유의미한 수치 향상이 관찰되었습니다. 이는 특히 대규모 애플리케이션 환경에서 큰 강점으로 작용할 것입니다.\n\n> "Next.js 15는 웹 개발의 복잡성을 줄이고, 훌륭한 사용자 경험을 제공하는 데 집중할 수 있게 해줍니다."\n\n결론적으로 Next.js 15는 우리가 웹을 구축하는 방식을 근본적으로 바꿔놓을 잠재력이 충분하다고 평가됩니다.', (SELECT id FROM public.categories WHERE name = 'Next.js'), 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800'),
('Mastering React Server Components', 'A comprehensive guide to leveraging Server Components for performance.', '## React Server Components의 이해\n\nReact Server Components(RSC)는 컴포넌트를 서버 환경에서만 렌더링하고, 클라이언트로는 결과물(주로 직렬화된 UI 트리)만 전송하는 혁신적인 아키텍처입니다.\n\n### 왜 RSC가 필요한가?\n\n*   **Zero Bundle Size**: 서버에서만 동작하는 컴포넌트의 코드는 클라이언트 번들에 포함되지 않습니다.\n*   **Direct Backend Access**: 데이터베이스나 파일 시스템 등에 직접 접근할 수 있어, 복잡한 API 레이어 구현을 줄일 수 있습니다.\n*   **Automatic Code Splitting**: 클라이언트 컴포넌트를 import 할 때 자동으로 코드 분할이 적용됩니다.\n\n### 사용 예제\n\n서버 컴포넌트에서 데이터베이스에 직접 쿼리하는 방식은 직관적입니다.\n\n```tsx\nimport db from \"./db\"\n\nexport default async function Note() {\n  // 서버에서 안전하게 직접 데이터베이스 쿼리를 실행합니다.\n  const note = await db.notes.get(1)\n  return <div>{note.text}</div>\n}\n```\n\nRSC를 효율적으로 다루는 것은 현대 웹 서비스의 성능 최적화를 위한 필수불가결한 스킬로 자리 잡고 있습니다.', (SELECT id FROM public.categories WHERE name = 'React'), 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&q=80&w=800'),
('The Future of Web Development', 'Exploring the upcoming trends and technologies in the web ecosystem.', '## 다가오는 웹의 미래 트렌드\n\n웹 개발 환경은 놀라운 속도로 진화하고 있습니다. 향후 몇 년간 주도할 핵심 트렌드들을 미리 살펴보고 대비하는 것이 중요합니다.\n\n### 주목해야 할 주요 기술 동향\n\n- **AI 기반 코딩 어시스턴트**: 개발 생산성을 획기적으로 높여주고, 코드 품질 검토부터 자동화된 테스트 작성까지 그 역할이 확장되고 있습니다.\n- **Wasm (WebAssembly)**: 브라우저 내에서 C++, Rust 등 고성능 언어가 네이티브 앱에 준하는 속도로 실행될 수 있게 되어, 더 무거운 연산이 필요한 웹 애플리케이션 개발이 활성화되고 있습니다.\n- **Edge Computing**: 사용자와 물리적으로 가까운 위치(Edge)에서 데이터를 처리함으로써 응답 지연 시간(Latency)을 최소화하는 아키텍처가 각광받고 있습니다.\n\n빠르게 변화하는 파도 속에서, 새로운 툴과 패러다임을 지속적으로 익히며 적응해 나가는 자세가 그 어느 때보다 필요한 시점입니다.', (SELECT id FROM public.categories WHERE name = 'Web'), 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=800'),
('Getting Started with Tailwind CSS v4', 'Learn how to style your applications efficiently with utility classes.', '## 왜 여전히 Tailwind CSS 일까?\n\n유틸리티 우선(Utility-first) CSS 프레임워크인 Tailwind CSS의 최신 버전이 가져온 변화를 알아봅니다. 클래스 이름 짓기에 대한 고민을 없애주고, HTML과 CSS 사이 컨텍스트 스위칭 비용을 최소화해 주는 강력한 툴입니다.\n\n### v4에서 기대할 수 있는 점\n*   **더 빠른 엔진**: 렌더링 성능이 최적화되어, 거대한 프로젝트에서도 빌드 속도가 쾌적합니다.\n*   **현대화된 디자인 토큰**: 최신 트렌드를 반영한 더 세련된 색상표와 기본 스케일 값들이 제공됩니다.\n*   **자동 벤더 프리픽스 개선**: 크로스 브라우징 이슈를 덜어주는 설정이 한층 똑똑해졌습니다.\n\nTailwind 특유의 직관성과 속도는 팀 단위 작업에서 컨벤션을 단일화하는 데 탁월한 효과를 발휘합니다. 지금 바로 프로젝트에 적용하여 빠른 스타일링을 경험해 보세요.', (SELECT id FROM public.categories WHERE name = 'CSS'), 'https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&q=80&w=800'),
('Building Secure APIs with Supabase', 'Implement robust authentication and authorization utilizing Supabase features.', '## Supabase를 활용한 안전한 백엔드 구축 가이드\n\nSupabase는 단순한 데이터베이스 호스팅을 넘어 인증, 스토리지, 실시간 구독 등 백엔드 전반을 아우르는 훌륭한 BaaS 솔루션입니다. 특히 보안 측면에서 강력한 기능을 제공합니다.\n\n### Row Level Security (RLS)의 중요성\nPostgreSQL의 전반적인 RLS 기능을 손쉽게 활용할 수 있습니다. 각 유저가 자신이 생성한 데이터에만 접근하거나 수정할 수 있도록 정교하게 권한을 제어할 수 있습니다.\n\n*   `auth.uid() = user_id` 와 같은 간단한 정책 작성만으로 데이터 누출 사고를 미연에 방지합니다.\n*   Supabase Dashboard 시각화 도구를 통해 복잡한 정책도 쉽게 리뷰하고 테스트할 수 있습니다.\n\n단순히 빠른 개발이 목적이 아니라, 근본적으로 안전하고 확장 가능한 서비스를 원한다면 Supabase의 보안 기능들을 적극 활용해야 합니다.', (SELECT id FROM public.categories WHERE name = 'Backend'), 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800'),
('A Deep Dive into React Hooks', 'Understanding the mechanics and best practices of using hooks.', '## React Hooks 심층 분석: 클린 코드 작성하기\n\n클래스 컴포넌트의 복잡성에서 벗어나 함수형 프로그래밍의 간결함을 React에 가져다준 Hooks. 이제는 선택이 아닌 필수입니다. 기본 훅들의 원리를 명확히 이해하고 올바로 사용하는 방법을 짚어봅니다.\n\n### 핵심 Hooks 톺아보기\n\n1.  **useState와 불변성**: 상태를 업데이트할 때는 반드시 불변성(Immutability)을 지켜야 합니다. 객체나 배열의 상태를 다룰 때 발생하기 쉬운 오류들을 점검합니다.\n2.  **useEffect의 의존성 배열**: 가장 강력하지만 헷갈리기 쉬운 훅입니다. 의존성 배열을 생략할 때, 빈 배열일 때, 특정 값이 들어있을 때의 렌더링 사이클을 완벽히 통제해야 메모리 누수를 막을 수 있습니다.\n3.  **useMemo와 useCallback**: 성능 최적화 은탄환은 아닙니다. 남용 시 오히려 메모리를 더 소모할 수 있습니다. 렌더링 비용이 정말 큰 연산과, 참조 동등성(Reference Equality) 보장이 반드시 필요한 콜백에만 선별적으로 사용하세요.\n\n올바른 훅 사용 습관이 애플리케이션의 유지보수성을 극대화합니다.', (SELECT id FROM public.categories WHERE name = 'React'), 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800');
